name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # On Linux CI, skip macOS-only dependencies (rumps, pync)
          pip install spotipy qbittorrent-api requests beautifulsoup4 python-dotenv pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q